[package]
name = "wkb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
lazy_static = "1.4.0"
regex = "1.10.2"
unicode-normalization = "0.1.22"
xkb-parser = { git = "https://github.com/rano-oss/xkb-parser.git" }
xkbcommon = "0.7.0"

[dev-dependencies]
test-case = "3.3.1"
xkbcommon = "0.7.0"

[build-dependencies]
xkbcommon = "0.7.0"
xkb-parser = { git = "https://github.com/rano-oss/xkb-parser.git" }
