[package]
name = "wkb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.10.2"
xkb-parser = { path = "/home/eivind/Public/code/xkb-parser" }
