// Common imports shared by xkbcomp modules.
// Generated from analysis of action.rs, compat.rs, expr.rs, keycodes.rs,
// keymap.rs, symbols.rs, types.rs.
// Category A (5+ files) and Category B (3-4 files) imports.

// context
pub use crate::context::xkb_atom_text;

// keymap
pub use crate::keymap::xkb_escape_map_name;

// messages
pub use crate::messages::{
    XKB_ERROR_ALLOCATION_ERROR, XKB_ERROR_CONFLICTING_KEY_SYMBOLS_ENTRY,
    XKB_ERROR_GLOBAL_DEFAULTS_WRONG_SCOPE, XKB_ERROR_INCOMPATIBLE_KEYMAP_TEXT_FORMAT,
    XKB_ERROR_INTEGER_OVERFLOW, XKB_ERROR_INVALID_ACTION_FIELD, XKB_ERROR_INVALID_EXPRESSION_TYPE,
    XKB_ERROR_INVALID_IDENTIFIER, XKB_ERROR_INVALID_MODMAP_ENTRY, XKB_ERROR_INVALID_OPERATION,
    XKB_ERROR_INVALID_REAL_MODIFIER, XKB_ERROR_INVALID_SET_DEFAULT_STATEMENT,
    XKB_ERROR_INVALID_VALUE, XKB_ERROR_INVALID_XKB_SYNTAX, XKB_ERROR_OVERLAPPING_OVERLAY,
    XKB_ERROR_UNDECLARED_VIRTUAL_MODIFIER, XKB_ERROR_UNKNOWN_ACTION_TYPE,
    XKB_ERROR_UNKNOWN_DEFAULT_FIELD, XKB_ERROR_UNKNOWN_FIELD, XKB_ERROR_UNKNOWN_OPERATOR,
    XKB_ERROR_UNKNOWN_STATEMENT, XKB_ERROR_UNSUPPORTED_LAYOUT_INDEX_,
    XKB_ERROR_UNSUPPORTED_MODIFIER_MASK_, XKB_ERROR_UNSUPPORTED_OVERLAY_INDEX,
    XKB_ERROR_UNSUPPORTED_SHIFT_LEVEL, XKB_ERROR_WRONG_FIELD_TYPE, XKB_ERROR_WRONG_STATEMENT_TYPE,
    XKB_WARNING_CANNOT_INFER_KEY_TYPE, XKB_WARNING_CONFLICTING_KEY_ACTION,
    XKB_WARNING_CONFLICTING_KEY_FIELDS, XKB_WARNING_CONFLICTING_KEY_NAME,
    XKB_WARNING_CONFLICTING_KEY_SYMBOL, XKB_WARNING_CONFLICTING_KEY_TYPE_DEFINITIONS,
    XKB_WARNING_CONFLICTING_KEY_TYPE_LEVEL_NAMES, XKB_WARNING_CONFLICTING_KEY_TYPE_MAP_ENTRY,
    XKB_WARNING_CONFLICTING_KEY_TYPE_MERGING_GROUPS,
    XKB_WARNING_CONFLICTING_KEY_TYPE_PRESERVE_ENTRIES, XKB_WARNING_CONFLICTING_MODMAP,
    XKB_WARNING_DUPLICATE_ENTRY, XKB_WARNING_EXTRA_SYMBOLS_IGNORED,
    XKB_WARNING_ILLEGAL_KEY_TYPE_PRESERVE_RESULT, XKB_WARNING_MISSING_SYMBOLS_GROUP_NAME_INDEX,
    XKB_WARNING_MULTIPLE_GROUPS_AT_ONCE, XKB_WARNING_NON_BASE_GROUP_NAME,
    XKB_WARNING_UNDECLARED_MODIFIERS_IN_KEY_TYPE, XKB_WARNING_UNDEFINED_KEYCODE,
    XKB_WARNING_UNDEFINED_KEY_TYPE, XKB_WARNING_UNRESOLVED_KEYMAP_SYMBOL,
    XKB_WARNING_UNSUPPORTED_GEOMETRY_SECTION, XKB_WARNING_UNSUPPORTED_LEGACY_ACTION,
    XKB_WARNING_UNSUPPORTED_SYMBOLS_FIELD,
};

// shared_ast_types
pub use crate::shared_ast_types::{
    merge_mode, pending_computation, safe_map_name, stmt_type_to_string, xkb_keymap_info, ExprDef,
    ExprKind, IncludeStmt, ReportBadType, Statement, VarDef, XkbFile, XkbcompFeatures,
    XkbcompLookup, FILE_TYPE_COMPAT, FILE_TYPE_GEOMETRY, FILE_TYPE_KEYCODES, FILE_TYPE_SYMBOLS,
    FILE_TYPE_TYPES, FIRST_KEYMAP_FILE_TYPE, LAST_KEYMAP_FILE_TYPE, MERGE_AUGMENT, MERGE_DEFAULT,
    MERGE_OVERRIDE, MERGE_REPLACE, PARSER_FATAL_ERROR, PARSER_NO_FIELD_TYPE_MISMATCH,
    PARSER_NO_FIELD_VALUE_MISMATCH, PARSER_NO_ILLEGAL_ACTION_FIELDS, PARSER_NO_UNKNOWN_ACTION,
    PARSER_NO_UNKNOWN_ACTION_FIELDS, PARSER_NO_UNKNOWN_COMPAT_GLOBAL_FIELDS,
    PARSER_NO_UNKNOWN_INTERPRET_FIELDS, PARSER_NO_UNKNOWN_KEYCODES_GLOBAL_FIELDS,
    PARSER_NO_UNKNOWN_KEY_FIELDS, PARSER_NO_UNKNOWN_LED_FIELDS, PARSER_NO_UNKNOWN_STATEMENTS,
    PARSER_NO_UNKNOWN_SYMBOLS_GLOBAL_FIELDS, PARSER_NO_UNKNOWN_TYPES_GLOBAL_FIELDS,
    PARSER_NO_UNKNOWN_TYPE_FIELDS, PARSER_RECOVERABLE_ERROR, PARSER_SUCCESS, PARSER_V1_LAX_FLAGS,
    PARSER_V1_STRICT_FLAGS, PARSER_V2_LAX_FLAGS, PARSER_V2_STRICT_FLAGS, STMT_EXPR_ACTION_DECL,
    STMT_EXPR_ACTION_LIST, STMT_EXPR_ASSIGN, STMT_EXPR_DIVIDE, STMT_EXPR_EMPTY_LIST,
    STMT_EXPR_IDENT, STMT_EXPR_INVERT, STMT_EXPR_KEYNAME_LITERAL, STMT_EXPR_KEYSYM_LIST,
    STMT_EXPR_KEYSYM_LITERAL, STMT_EXPR_NEGATE, STMT_EXPR_NOT, STMT_EXPR_UNARY_PLUS,
    STMT_UNKNOWN_COMPOUND,
};

// shared_types
pub use crate::shared_types::{
    xkb_action_controls, xkb_action_flags, xkb_explicit_components, xkb_keymap,
    xkb_overlay_index_t, xkb_overlay_mask_t, ACTION_ABSOLUTE_SWITCH, ACTION_ABSOLUTE_X,
    ACTION_ABSOLUTE_Y, ACTION_ACCEL, ACTION_LATCH_ON_PRESS, ACTION_LATCH_TO_LOCK,
    ACTION_LOCK_CLEAR, ACTION_LOCK_NO_LOCK, ACTION_LOCK_NO_UNLOCK, ACTION_LOCK_ON_RELEASE,
    ACTION_MODS_LOOKUP_MODMAP, ACTION_PENDING_COMPUTATION, ACTION_SAME_SCREEN,
    ACTION_TYPE_CTRL_LOCK, ACTION_TYPE_GROUP_LATCH, ACTION_TYPE_GROUP_LOCK, ACTION_TYPE_GROUP_SET,
    ACTION_TYPE_MOD_LATCH, ACTION_TYPE_MOD_LOCK, ACTION_TYPE_MOD_SET, ACTION_TYPE_NONE,
    ACTION_TYPE_PRIVATE, ACTION_TYPE_PTR_DEFAULT, ACTION_TYPE_PTR_LOCK, ACTION_TYPE_PTR_MOVE,
    ACTION_TYPE_REDIRECT_KEY, ACTION_TYPE_SWITCH_VT, ACTION_TYPE_UNKNOWN,
    ACTION_TYPE_UNSUPPORTED_LEGACY, ACTION_UNLOCK_ON_PRESS, DEFAULT_INTERPRET_KEY_REPEAT,
    DEFAULT_INTERPRET_VMOD, EXPLICIT_INTERP, EXPLICIT_OVERLAY, EXPLICIT_REPEAT, EXPLICIT_SYMBOLS,
    EXPLICIT_TYPES, EXPLICIT_VMODMAP, MATCH_ALL, MATCH_ANY, MATCH_ANY_OR_NONE, MATCH_EXACTLY,
    MATCH_NONE, MOD_BOTH, MOD_REAL, MOD_VIRT, XKB_ERROR_UNSUPPORTED_LAYOUT_INDEX,
    XKB_ERROR_UNSUPPORTED_MODIFIER_MASK, _ACTION_TYPE_NUM_ENTRIES,
};

// text
pub use crate::text::{ActionTypeText, KeysymText, LookupEntry};

// xkbcomp submodules
pub use crate::xkbcomp::expr::{
    ExprResolveBoolean, ExprResolveEnum, ExprResolveGroup, ExprResolveLhs, ExprResolveModMask,
    ExprResolveString,
};

pub use crate::xkbcomp::include::{ExceedsIncludeMaxDepth, ProcessIncludeFile};

pub use crate::xkbcomp::vmod::{HandleVModDef, InitVMods, MergeModSets};
