//! Generate wkb layout data files.
//!
//! Reads the XKB registry (`rules/evdev.xml`) and writes:
//!
//! 1. `test_data/layouts.rs` — the static `(layout, variant)` registry used by
//!    integration tests via `include!`.
//! 2. `ron_layouts/` — precompiled `wkb::ir` RON files for every layout,
//!    mirroring the naming convention `<layout>.<variant>.ron` (base layout:
//!    `<layout>.ron`).
//!
//! ```sh
//! cargo run --example gen_layouts [path/to/evdev.xml]
//! ```

use std::path::{Path, PathBuf};

use quick_xml::events::Event;
use quick_xml::Reader;
use wkb::WKB;

const EVDEV_XML: &str = "/usr/share/X11/xkb/rules/evdev.xml";
const OUT_DIR: &str = "ron_layouts";
const LAYOUTS_RS: &str = "test_data/layouts.rs";

fn main() {
    let xml_path = std::env::args()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(EVDEV_XML));
    let layouts = read_layouts(&xml_path).expect("failed to parse XKB registry");
    println!(
        "found {} layout(s)/variant(s) in {}",
        layouts.len(),
        xml_path.display()
    );

    write_layouts_rs(&layouts);

    let out_dir = PathBuf::from(OUT_DIR);
    std::fs::create_dir_all(&out_dir).expect("failed to create output directory");

    let mut written = 0usize;
    let mut skipped = 0usize;
    for (layout, variant) in &layouts {
        let path = out_dir.join(file_name(layout, variant));
        let text = match generate(layout, variant) {
            Ok(text) => text,
            Err(err) => {
                eprintln!("skipped {} ({}): {err}", layout, variant);
                skipped += 1;
                continue;
            }
        };
        std::fs::write(&path, text).expect("failed to write output file");
        written += 1;
    }

    println!("wrote {written} file(s) to {OUT_DIR}/, skipped {skipped}");
}

/// Enumerate all `(layout, variant)` pairs from the XKB registry.
fn read_layouts(path: &Path) -> Result<Vec<(String, String)>, quick_xml::Error> {
    let mut reader = Reader::from_file(path)?;
    reader.config_mut().trim_text(true);

    let mut stack: Vec<String> = Vec::new();
    let mut current_layout: Option<String> = None;
    let mut pairs: Vec<(String, String)> = Vec::new();
    let mut buf = Vec::new();

    loop {
        match reader.read_event_into(&mut buf)? {
            Event::Start(e) => {
                stack.push(String::from_utf8_lossy(e.name().as_ref()).into_owned());
            }
            Event::End(e) => {
                let name = String::from_utf8_lossy(e.name().as_ref()).into_owned();
                if name == "layout" {
                    current_layout = None;
                }
                stack.pop();
            }
            Event::Text(t) => {
                let text = t.unescape()?.into_owned();
                if text.is_empty() {
                    continue;
                }
                let depth = stack.len();
                if depth >= 2 && stack[depth - 1] == "name" && stack[depth - 2] == "configItem" {
                    if let Some(lp) = stack.iter().rposition(|s| s == "layout") {
                        if stack[lp..].iter().any(|s| s == "variant") {
                            if let Some(base) = &current_layout {
                                pairs.push((base.clone(), text));
                            }
                        } else {
                            pairs.push((text.clone(), String::new()));
                            current_layout = Some(text);
                        }
                    }
                }
            }
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(pairs)
}

fn write_layouts_rs(layouts: &[(String, String)]) {
    let mut text = String::new();
    text.push_str("// Static layout registry for wkb integration tests.\n");
    text.push_str("//\n");
    text.push_str("// Generated by `examples/gen_layouts.rs` from the XKB registry\n");
    text.push_str("// (`rules/evdev.xml`). Layouts/locales are static, so this list is baked\n");
    text.push_str("// in instead of parsing the registry at runtime.\n");
    text.push_str("//\n");
    text.push_str("// Do not edit by hand — regenerate with `cargo run --example gen_layouts`.\n");
    text.push_str("\n");
    text.push_str("/// All `(layout, variant)` pairs from the XKB registry. The base layout\n");
    text.push_str("/// has an empty variant.\n");
    text.push_str("pub static LAYOUTS: &[(&str, &str)] = &[\n");
    for (layout, variant) in layouts {
        text.push_str(&format!("    (\"{layout}\", \"{variant}\"),\n"));
    }
    text.push_str("];\n");
    text.push_str("\n");
    text.push_str("/// List all available `(layout, variant)` pairs from the static registry.\n");
    text.push_str("/// Returns pairs suitable for `WKB::new_from_names`. The base layout has an\n");
    text.push_str("/// empty variant string.\n");
    text.push_str("pub fn list_layouts() -> Vec<(String, String)> {\n");
    text.push_str("    LAYOUTS\n");
    text.push_str("        .iter()\n");
    text.push_str("        .map(|&(layout, variant)| (layout.to_string(), variant.to_string()))\n");
    text.push_str("        .collect()\n");
    text.push_str("}\n");
    text.push_str("\n");
    text.push_str("/// Get all available layout variants for a given locale (test utility).\n");
    text.push_str("pub fn get_all_layouts_for_locale(locale: &str) -> Vec<String> {\n");
    text.push_str("    let mut layouts: Vec<String> = LAYOUTS\n");
    text.push_str("        .iter()\n");
    text.push_str("        .filter(|&&(layout, _)| layout == locale)\n");
    text.push_str("        .map(|&(_, variant)| variant.to_string())\n");
    text.push_str("        .collect();\n");
    text.push_str("    if layouts.is_empty() {\n");
    text.push_str("        layouts.push(String::new());\n");
    text.push_str("    }\n");
    text.push_str("    layouts\n");
    text.push_str("}\n");
    std::fs::create_dir_all("test_data").expect("failed to create test_data dir");
    std::fs::write(LAYOUTS_RS, text).expect("failed to write layouts.rs");
    println!("wrote {LAYOUTS_RS}");
}

fn generate(layout: &str, variant: &str) -> Result<String, String> {
    let wkb = WKB::new_from_names("", "", layout, variant, None).map_err(|err| err.to_string())?;
    let file = wkb.export_layout(0).map_err(|err| err.to_string())?;
    file.to_ron_string().map_err(|err| err.to_string())
}

fn file_name(layout: &str, variant: &str) -> String {
    if variant.is_empty() {
        format!("{layout}.ron")
    } else {
        format!("{layout}.{variant}.ron")
    }
}
